bw_min: 5.0
bw_max: 20.0
rtt_min: 20
rtt_max: 100
qmin: 10
qmax: 200
pkt_min: 1000
pkt_max: 2000
loss_min: 0.0
loss_max: 0.02
enable_cross_traffic: false
cross_start_prob: 0.02
cross_dur_min: 1
cross_dur_max: 6
cross_rate: 5.0